INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (001,	'af',	'Afrikaans');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (002,	'sq',	'Shqip');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (003,	'am',	'አማርኛ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (004,	'ar',	'العربية');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (005,	'hy',	'Հայերեն');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (006,	'az',	'azərbaycan dili');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (007,	'eu',	'euskara');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (008,	'be',	'беларуская мова');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (009,	'bn',	'বাংলা');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (010,	'bs',	'bosanski jezik');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (011,	'bg',	'български език');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (012,	'ca',	'català');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (013,	'ceb',	'Cebuano');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (014,	'zh',	'中文');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (015,	'co',	'corsu');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (016,	'hr',	'hrvatski jezik');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (017,	'cs',	'čeština');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (018,	'da',	'dansk');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (019,	'nl',	'Nederlands');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (020,	'en',	'English');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (021,	'eo',	'Esperanto');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (022,	'et',	'eesti');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (023,	'fi',	'suomi');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (024,	'fr',	'français');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (025,	'fy',	'Frysk');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (026,	'gl',	'Galego');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (027,	'ka',	'ქართული');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (028,	'de',	'Deutsch');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (029,	'el',	'ελληνικά');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (030,	'gu',	'ગુજરાતી');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (031,	'ht',	'Kreyòl ayisyen');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (032,	'ha',	'هَوُسَ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (033,	'haw',	'&#x27;Ōlelo Hawai&#x27;i');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (034,	'iw',	'עברית');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (035,	'hi',	'हिन्दी, हिंदी');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (036,	'hmn',	'Hmoob');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (037,	'hu',	'magyar');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (038,	'is',	'Íslenska');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (039,	'ig',	'Asụsụ Igbo');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (040,	'id',	'Bahasa Indonesia');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (041,	'ga',	'Gaeilge');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (042,	'it',	'Italiano');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (043,	'ja',	'日本語');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (044,	'jw',	'Basa Jawa');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (045,	'kn',	'ಕನ್ನಡ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (046,	'kk',	'қазақ тілі');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (047,	'km',	'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (048,	'ko',	'한국어');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (049,	'ku',	'Kurdî');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (050,	'ky',	'Кыргызча');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (051,	'lo',	'ພາສາລາວ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (052,	'la',	'latine');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (053,	'lv',	'Latviešu');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (054,	'lt',	'lietuvių kalba');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (055,	'lb',	'Lëtzebuergesch');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (056,	'mk',	'македонски јазик');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (057,	'mg',	'fiteny malagasy');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (058,	'ms',	'بهاس ملايو');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (059,	'ml',	'മലയാളം');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (060,	'mt',	'Malti');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (061,	'mi',	'te reo Māori');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (062,	'mr',	'मराठी');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (063,	'mn',	'Монгол хэл');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (064,	'my',	'ဗမာစာ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (065,	'ne',	'नेपाली');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (066,	'no',	'Norsk');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (067,	'ny',	'chinyanja');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (068,	'ps',	'پښتو');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (069,	'fa',	'فارسی');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (070,	'pl',	'język polski');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (071,	'pt',	'Português');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (072,	'pa',	'ਪੰਜਾਬੀ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (073,	'ro',	'Română');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (074,	'ru',	'Русский');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (075,	'sm',	'gagana fa&#x27;a Samoa');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (076,	'gd',	'Gàidhlig');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (077,	'sr',	'српски језик');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (078,	'st',	'Sesotho');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (079,	'sn',	'chiShona');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (080,	'sd',	'सिन्धी');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (081,	'si',	'සිංහල');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (082,	'sk',	'Slovenčina');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (083,	'sl',	'Slovenski Jezik');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (084,	'so',	'Soomaaliga');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (085,	'es',	'Español');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (086,	'su',	'Basa Sunda');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (087,	'sw',	'Kiswahili');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (088,	'sv',	'Svenska');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (089,	'tl',	'Wikang Tagalog');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (090,	'tg',	'тоҷикӣ');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (091,	'ta',	'தமிழ்');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (092,	'te',	'తెలుగు');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (093,	'th',	'ไทย');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (094,	'tr',	'Türkçe');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (095,	'uk',	'Українська');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (096,	'ur',	'اردو');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (097,	'uz',	'Ўзбек');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (098,	'vi',	'Tiếng Việt');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (099,	'cy',	'Cymraeg');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (100,	'xh',	'isiXhosa');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (101,	'yi',	'ייִדיש');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (102,	'yo',	'Yorùbá');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (103,	'zu',	'isiZulu');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (104,	'kp',	'조선말');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (105,	'kr',	'한국어');
INSERT INTO Languages (	idLang,	langLyrics,	nameLang ) VALUES (106,	'ins',	'Instrumental');